topic: Meta Learning
papers:
  - title: Human-level concept learning through probabilistic program induction
    date: 2015-12-11
    proceeding: Science 2015
    pdf: https://www.cs.cmu.edu/~rsalakhu/papers/LakeEtAl2015Science.pdf
    stress: true
  - title: "Meta-Learning: Learning to Learn Fast"
    link: https://lilianweng.github.io/lil-log/2018/11/30/meta-learning.html
    date: 2018-11-30
references:
  - title: Learning to Learn
    link: https://bair.berkeley.edu/blog/2017/07/18/learning-to-learn/
